#! /usr/bin/env bash
# vim: tabstop=4 shiftwidth=4 expandtab
#
#++
#   ==============
#   Wrapper script
#   ==============
#   :Author: Adrián Pérez <aperez@igalia.com>
#   :Copyright: Igalia S.L., 2008
#   :License: GPL v2
#   :Abstract: Wrapper which launches the bash_ shell adding the Bill
#       built-in functions.
#--
set -e

[ "$BILL_DEBUG" ] && set -x

libdir=/usr/lib/bill
if [ ! -d "$libdir" ]
then
    pushd "$(dirname "$0")/../lib" > /dev/null
    libdir=$(pwd)
    popd > /dev/null
fi

if [ "$BILLPATH" ]
then
    BILLPATH="$libdir:$BILLPATH"
else
    BILLPATH="$libdir"
fi
unset libdir
export BILLPATH


#++ use module
#
#   Loads one module from the library search path, which is itself
#   taken from the ``$BILLPATH`` environment variable. If a module is not
#   found, execution will be aborted and an informative message will be
#   printed to standard error.
#
#   Note that this is a stripped down version used only in this script for
#   performing bootstrap, once the `bill/builtins <bill/builtins.html>`_
#   module gets loaded a more complete version of the function will be
#   available.
#--
use ()
{
    local old_IFS=$IFS
    local found=false
    local path

    IFS=':'
    for path in $BILLPATH
    do
        if [ -r "$path/$1.bsh" ]
        then
            source "$path/$1.bsh"
            found=true
            break
        fi
    done

    # Sanity check :)
    if ! $found
    then
        ( echo "Could not find module '$1', the module search path is"
          echo "  $BILLPATH"
        ) 1>&2
        exit 1
    fi
    IFS=$old_IFS
}

use bill/builtins

if [ "$1" ]
then
    SCRIPT=$1
    shift
    BILLPATH="$(dirname "$SCRIPT"):$BILLPATH"
    source "$SCRIPT"
else
    unset PROMPT_COMMAND
    PS1='\[\033[1;1m\](bill)\[\033[0;0m\] '
    PS2='\[\033[1;1m\]  ...)\[\033[0;0m\] '
    BILLPATH="$(pwd):$BILLPATH"

    # XXX This crude hack works because we are exporting built-in functions
    #      using "declare -xf" AND as we do not redirect stdin/stdout for
    #      the new shell, it will start as an interactive one. As it will
    #      get a real terminal, it will start in interactive mode with the
    #      desired settings.
    #
    export BILL_VERSION BILLPATH PS1 PS2
    exec < /dev/tty &> /dev/tty
    exec bash --noprofile --norc
fi

